server:
  port: ${PORT:${SERVER_PORT:8082}}

jwt:
  secret: ${JWT_SECRET:AxXLZtEnBsZcWCG6uBC0wCGYCRhrV2D+XVg08SNlk8yt4JQ9Ga/hgaSuqhDlL2qDLA9vDOPqVlNJQyxKBAW87Q==}
  issuer: https://microservices.iam.local
  audience: movie-service
  expiration-minutes: 60
  refresh-expiration-days: 7

spring:
  application:
    name: movie-service
    
  datasource:
    url: ${SPRING_DATASOURCE_URL_MOVIE:jdbc:postgresql://localhost:5432/MovieService}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

grpc:
  server:
    port: 9091

# Movie service specific configurations
movie:
  seat-lock:
    duration-minutes: 10
  payment:
    mock-success-rate: 0.9
  booking:
    cancellation-window-hours: 2