server:
  port: ${PORT:${SERVER_PORT:8081}}

jwt:
  secret: ${JWT_SECRET:AxXLZtEnBsZcWCG6uBC0wCGYCRhrV2D+XVg08SNlk8yt4JQ9Ga/hgaSuqhDlL2qDLA9vDOPqVlNJQyxKBAW87Q==}
  issuer: https://microservices.iam.local
  audience: profile-service
  expiration-minutes: 60
  refresh-expiration-days: 7

oauth2:
  authorization-code-ttl-seconds: 600

spring:
  application:
    name: profile-service
  datasource:
    url: ${SPRING_DATASOURCE_URL_PROFILE:jdbc:postgresql://localhost:5432/MicroServices}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
grpc:
  server:
    port: 9090

security:
  encryption:
    key: ${SECURITY_ENCRYPTION_KEY:${PROFILE_SECURITY_ENCRYPTION_KEY:figpZBcjVG/dZjqLwbj8Q0a9zTl+OqcO9ldJnOExohA=}}
