server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}
  issuer: https://microservices.iam.local
  audience: profile-service
  expiration-minutes: 60
  refresh-expiration-days: 7

oauth2:
  authorization-code-ttl-seconds: 600

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL_PROFILE}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
grpc:
  server:
    port: 9090

security:
  encryption:
    key: ${SECURITY_ENCRYPTION_KEY}
