server:
  port: ${PORT:${SERVER_PORT:8080}}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

jwt:
  secret: ${JWT_SECRET:AxXLZtEnBsZcWCG6uBC0wCGYCRhrV2D+XVg08SNlk8yt4JQ9Ga/hgaSuqhDlL2qDLA9vDOPqVlNJQyxKBAW87Q==}
  issuer: https://microservices.iam.local
  audience: profile-service

#spring:
#  data:
#    redis:
#      host: localhost
#      port: 6379
#  session:
#    store-type: redis
#    timeout: 30m
#    redis:
#      namespace: spring:session

oauth2:
  frontend:
    base-url: ${OAUTH2_FRONTEND_BASE_URL:http://localhost:4200}
    login-path: /login
    consent-path: /oauth-consent

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}

#  cloud:
#    gateway:
#      routes:
#        - id: auth-route
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/v1/users/login,/api/v1/users/register
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 100
#                redis-rate-limiter.burstCapacity: 200
#                key-resolver: "#{@userKeyResolver}"
#        - id: protected-route
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/v1/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 50
#                redis-rate-limiter.burstCapacity: 100
#                key-resolver: "#{@userKeyResolver}"

logging:
  level:
    com.microservices: INFO
    org.springframework.security: DEBUG
    io.jsonwebtoken: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

grpc:
  client:
    profile-service:
      address: ${GRPC_CLIENT_PROFILE_SERVICE_ADDRESS:static://localhost:9090}
      negotiationType: plaintext

    address-service:
      address: ${GRPC_CLIENT_ADDRESS_SERVICE_ADDRESS:static://localhost:9090}
      negotiationType: plaintext

    mfa-service:
      address: ${GRPC_CLIENT_MFA_SERVICE_ADDRESS:static://localhost:9090}
      negotiationType: plaintext

    movie-service:
      address: ${GRPC_CLIENT_MOVIE_SERVICE_ADDRESS:static://localhost:9091}
      negotiationType: plaintext

    image-service:
      address: ${GRPC_CLIENT_IMAGE_SERVICE_ADDRESS:static://localhost:9091}
      negotiationType: plaintext

    theater-service:
      address: ${GRPC_CLIENT_THEATER_SERVICE_ADDRESS:static://localhost:9091}
      negotiationType: plaintext