name: Trigger auto deployment for movie-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/movie-backend-AutoDeployTrigger-5b67d947-b331-4383-9f18-bf419a5b8d9b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MOVIEBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MOVIEBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MOVIEBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.MOVIEBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MOVIEBACKEND_REGISTRY_PASSWORD }}
          containerAppName: movie-backend
          resourceGroup: Movie_Platform
          imageToBuild: removino68/movie-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


